apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grafana-otel-lgtm.fullname" . }}-pvc
  labels:
    {{- include "grafana-otel-lgtm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: {{ include "grafana-otel-lgtm.fullname" . }}-pv